name: 'Prepare'
description: 'Prepare everything'
inputs:
  node-version:
    description: 'Node Version'
    required: false
    default: '20'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - name: Install dependencies
      shell: bash
      run: npm ci
